name: 'Send feishu notice'
description: '发送飞书服务发布消息'
inputs:
  notice-title:
    description: 消息卡片标题
    required: true
  notice-color:
    description: 消息卡片颜色
    required: true
  button-text:
    description: 按钮文本
    required: true
  button-link:
    description: 按钮链接
    required: true
  webhook-url:
    description: 飞书消息通知 webhook url
    required: true
  notice-markdown:
    description: 消息 markdown 内容
    required: true
runs:
  using: "composite"
  steps:
    - id: send-notice
      env:
        NOTICE_COLOR: ${{ inputs.notice-color }}
        BUTTON_TEXT: ${{ inputs.button-text }}
        BUTTON_LINK: ${{ inputs.button-link }}
        WEBHOOK_URL: ${{ inputs.webhook-url }}
        COMMIT_MESSAGE: ${{ toJSON(github.event.head_commit.message || github.event.workflow_run.head_commit.message) }}
        NOTICE_TITLE: "${{ inputs.notice-title }}"
        NOTICE_MARKDOWN: ${{ toJSON(inputs.notice-markdown) }}
      run: |
          export TZ='Asia/Shanghai'
          DATE_TIME=$(date +'%Y-%m-%d %H:%M:%S')
          curl -X POST "${WEBHOOK_URL}" \
          --header 'Content-Type: application/json' \
          --data-raw "$(cat <<EOF
          {"msg_type":"interactive","card":{"config":{"wide_screen_mode":true},"elements":[{"tag":"note","elements":[{"tag":"plain_text","content":"${DATE_TIME}"}]},{"tag":"markdown","content":${NOTICE_MARKDOWN}},{"tag":"hr"},{"tag":"div","text":{"content":${COMMIT_MESSAGE},"tag":"plain_text"}},{"tag":"hr"},{"tag":"action","actions":[{"tag":"button","text":{"tag":"plain_text","content":"${BUTTON_TEXT}"},"type":"primary","multi_url":{"url":"${BUTTON_LINK}","pc_url":"","android_url":"","ios_url":""}}]}],"header":{"template":"${NOTICE_COLOR}","title":{"content":"${NOTICE_TITLE}","tag":"plain_text"}}}}
          EOF
          )"
      shell: bash
