name: 'Send feishu notice'
description: '发送飞书服务发布消息'
inputs:
  notice-title:
    description: 消息卡片标题
    required: true
  notice-color:
    description: 消息卡片颜色
    required: true
  button-text:
    description: 按钮文本
    required: true
  button-link:
    description: 按钮链接
    required: true
  feishu-webhook-url:
    description: 飞书消息通知 webhook url
    required: true
  notice-markdown:
    description: 消息 markdown 内容
    required: true
runs:
  using: "composite"
  steps:
    - id: send-notice
      env:
        NOTICE_COLOR: ${{ inputs.notice-color }}
        BUTTON_TEXT: ${{ inputs.button-text }}
        BUTTON_LINK: ${{ inputs.button-link }}
        FEISHU_WEBHOOK: ${{ inputs.feishu-webhook-url }}
        COMMIT_MESSAGE: ${{ toJSON(github.event.head_commit.message) }}
        NOTICE_MARKDOWN: ${{ inputs.notice-markdown }}
      run: |
          NOTICE_TITLE="${{ inputs.notice-title }} | $(date +'%Y-%m-%d %H:%M:%S')"
          cat <<EOF > post-data.json
          {"msg_type":"interactive","card":{"config":{"wide_screen_mode":true},"elements":[{"tag":"markdown","content":"'$NOTICE_MARKDOWN'"},{"tag":"hr"},{"tag":"div","text":{"content":${COMMIT_MESSAGE},"tag":"plain_text"}},{"tag":"hr"},{"tag":"action","actions":[{"tag":"button","text":{"tag":"plain_text","content":"'${BUTTON_TEXT}'"},"type":"primary","multi_url":{"url":"'${BUTTON_LINK}'","pc_url":"","android_url":"","ios_url":""}}]}],"header":{"template":"'${NOTICE_COLOR}'","title":{"content":"'${NOTICE_TITLE}'","tag":"plain_text"}}}}
          EOF
          cat post-data.json
          curl -X POST "${FEISHU_WEBHOOK}" \
          --header 'Content-Type: application/json' \
          -d @post-data.json
      shell: bash